include:
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: SAST.gitlab-ci.yml
  - template: Secret-Detection.gitlab-ci.yml

image: nexendrie/php:7.4

variables:
  URL_ALPHA: "https://alpha.nexendrie.cz"
  URL_BETA: "https://beta.nexendrie.cz"

stages:
  - install
  - test
  - deploy

.default_cache: &default_cache
  policy: pull
  paths:
    - vendor/

.test_job: &test_job
  stage: test
  services:
    - mariadb
  cache:
    <<: *default_cache
  variables:
    MYSQL_DATABASE: nexendrie
    MYSQL_ROOT_PASSWORD: root
  script:
    - phing test-ci
  retry: 2

.deploy_job: &deploy_job
  stage: deploy
  cache:
    <<: *default_cache
  dependencies: []
  script:
    - phing deploy

install:
  stage: install
  script:
    - composer install --prefer-dist --no-progress --no-suggest --no-interaction
  cache:
    <<: *default_cache
    policy: pull-push

sast:
  variables:
    SAST_DEFAULT_ANALYZERS: "eslint,phpcs-security-audit"
  cache:
    <<: *default_cache

test:default:
  <<: *test_job

test:php8.0:
  <<: *test_job
  image: nexendrie/php:8.0
  allow_failure: true
  retry: 0

test:php8.1:
  <<: *test_job
  image: nexendrie/php:8.1
  allow_failure: true
  retry: 0

test:cc:
  <<: *test_job
  script:
    - phing test-ci-coverage
  coverage: '/(\d+\%) covered/'
  artifacts:
    name: "Code coverage"
    paths:
      - coverage.html

test:css:
  stage: test
  image: nexendrie/nodejs
  script:
    - csslint www/styles

deploy:alpha:
  <<: *deploy_job
  environment:
    name: alpha
    url: $URL_ALPHA
  only:
    - master@nexendrie/nexendrie
  variables:
    DEPLOY_ENVIRONMENT: alpha

deploy:beta:
  <<: *deploy_job
  environment:
    name: beta
    url: $URL_BETA
  only:
    - tags@nexendrie/nexendrie
  variables:
    DEPLOY_ENVIRONMENT: beta
