include:
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml
  - template: Jobs/SAST.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml

stages:
  - install
  - test
  - deploy

.default_cache: &default_cache
  policy: pull
  paths:
    - vendor/

.test_job: &test_job
  stage: test
  services:
    - mariadb
  cache:
    <<: *default_cache
  variables:
    MYSQL_DATABASE: nexendrie
    MYSQL_ROOT_PASSWORD: root
  script:
    - phing test-ci
  retry: 2

.deploy_job: &deploy_job
  stage: deploy
  cache:
    <<: *default_cache
  dependencies: []
  script:
    - phing deploy

install:
  stage: install
  image: nexendrie/php:8.1
  script:
    - composer install --prefer-dist --no-progress --no-suggest --no-interaction
  cache:
    <<: *default_cache
    policy: pull-push

sast:
  variables:
    SAST_DEFAULT_ANALYZERS: "eslint,phpcs-security-audit"
  cache:
    <<: *default_cache

test:php8.1:
  <<: *test_job
  image: nexendrie/php:8.1

test:reports:
  extends:
    - .test_job
  image: nexendrie/php:8.1
  variables:
    REPORTS: 1
  coverage: '/(\d+\%) covered/'
  artifacts:
    paths:
      - coverage.xml
      - junit.xml
      - phpstan.json
    reports:
      junit: junit.xml
      codequality: phpstan.json

deploy:alpha:
  <<: *deploy_job
  image: nexendrie/php:8.1
  environment:
    name: alpha
    url: https://alpha.nexendrie.cz
    deployment_tier: testing
  only:
    - master@nexendrie/nexendrie
  variables:
    DEPLOY_ENVIRONMENT: alpha

deploy:beta:
  <<: *deploy_job
  image: nexendrie/php:8.1
  environment:
    name: beta
    url: https://beta.nexendrie.cz
    deployment_tier: staging
  only:
    - tags@nexendrie/nexendrie
  variables:
    DEPLOY_ENVIRONMENT: beta
