image: nexendrie/php:7.3

stages:
  - test
  - deploy

cache:
  paths:
    - vendor/

.test_job: &test_job
  stage: test

  services:
    - mariadb

  variables:
    MYSQL_DATABASE: nexendrie
    MYSQL_ROOT_PASSWORD: root

  script:
    - phing test-ci

.deploy_job: &deploy_job
  stage: deploy

  dependencies: []

  script:
    - phing deploy

test:default:
  <<: *test_job
  retry: 2

test:pgsql:
  <<: *test_job
  services:
    - postgres
  variables:
    POSTGRES_DB: nexendrie
    POSTGRES_USER: root
    POSTGRES_PASSWORD: root
  script:
    - phing test-ci-pgsql
  allow_failure: true

test:cc:
  <<: *test_job
  script:
    - phing test-ci-coverage
  coverage: '/(\d+\%) covered/'
  artifacts:
    name: "Code coverage"
    paths:
      - coverage.html
  retry: 2

test:css:
  stage: test
  image: node:lts-buster
  before_script:
    - npm install -g csslint
  script:
    - csslint styles

deploy:alpha:
  <<: *deploy_job
  environment:
    name: alpha
    url: https://alpha.nexendrie.cz
  only:
    - master@nexendrie/nexendrie
  variables:
    DEPLOY_ENVIRONMENT: alpha

deploy:beta:
  <<: *deploy_job
  environment:
    name: beta
    url: https://beta.nexendrie.cz
  only:
    - tags@nexendrie/nexendrie
  variables:
    DEPLOY_ENVIRONMENT: beta
