image: chialab/php:7.1

stages:
  - test
  - deploy

before_script:
- curl -sS https://www.phing.info/get/phing-latest.phar > phing
- chmod +x phing

.job_template: &test_job
  stage: test

  services:
  - mysql

  variables:
    MYSQL_DATABASE: nexendrie_test
    MYSQL_ROOT_PASSWORD: root
    APP_USER: admin
    APP_PASSWORD: qwerty

  script:
  - ./phing test-ci

.job_template: &deploy_job
  stage: deploy

  script:
  - ./phing deploy

test:default:
  <<: *test_job

test:cc:
  image: chialab/php-dev:7.1
  <<: *test_job
  script:
  - ./phing test-coverage
  coverage: '/(\d+\%) covered/'
  artifacts:
    name: "Code coverage"
    paths:
    - coverage.html

deploy:alpha:
  <<: *deploy_job
  environment:
    name: alpha
    url: http://alpha.nexendrie.cz
  only:
    - master@nexendrie/nexendrie
  variables:
    DEPLOY_ENVIRONMENT: alpha

deploy:beta:
  <<: *deploy_job
  environment:
    name: beta
    url: https://beta.nexendrie.cz
  only:
    - tags
  variables:
    DEPLOY_ENVIRONMENT: beta
