image: php:5.6

services:
- mysql

cache:
  paths:
  - vendor/

before_script:
- mkdir app/temp
- mkdir app/temp/cache
- mkdir app/temp/sessions
- mkdir app/log

- apt-get update -yqq
- apt-get install git -yqq
- docker-php-ext-install pdo_mysql
- curl -sS https://getcomposer.org/installer | php
- php composer.phar install --no-interaction --prefer-source

variables:
  MYSQL_DATABASE: nexendrie
  MYSQL_ROOT_PASSWORD: nexendrie

.job_template: &script_def
  script:
  - ./vendor/bin/parallel-lint app -e php --exclude vendor
  - ./vendor/bin/phpcs --extensions=php . --standard=ruleset.xml --colors

test:mysql:
  <<: *script_def

test:php7:mysql:
  image: php:7
  <<: *script_def

