image: shipito/php:7.0

stages:
  - build
  - analyze
  - test
  - deploy

build:
  stage: build

  script:
  - mkdir temp/cache
  - composer install --prefer-dist -a

  cache:
    paths:
    - vendor

  artifacts:
    paths:
    - vendor
    - temp/cache
    expire_in: 10 mins

analyze:lint:
  stage: analyze
  script:
  - ./vendor/bin/parallel-lint . -e php,phpt --exclude vendor --exclude temp --exclude tests/_temp

analyze:cs:
  stage: analyze

  before_script:
  - curl https://gitlab.com/nexendrie/resources/raw/master/cs-ruleset.xml > cs-ruleset.xml

  script:
  - ./vendor/bin/phpcs --extensions=php,phpt . --standard=cs-ruleset.xml --colors

.job_template: &test_job
  stage: test

  services:
  - mysql

  variables:
    MYSQL_DATABASE: nexendrie
    MYSQL_ROOT_PASSWORD: root
    APP_USER: admin
    APP_PASSWORD: qwerty

  before_script:
  - docker-php-ext-install mysqli
  - php ci/setup_db.php

  script:
  - ./vendor/bin/run-tests -p php tests

.job_template: &deploy_job
  stage: deploy

  dependencies:
  - build

  before_script:
  - php ci/prepare_deploy.php

  script:
  - ./vendor/bin/deployment deployment.ini

test:default:
  <<: *test_job

test:cc:
  image: shipito/php:7.0-xdebug
  <<: *test_job
  script:
  - ./vendor/bin/run-tests -p php tests --coverage ./coverage.html --coverage-src ./app
  artifacts:
    name: "Code coverage"
    paths:
    - coverage.html

test:php71:
  image: shipito/php:7.1
  <<: *test_job

deploy:alpha:
  <<: *deploy_job
  environment: alpha
  only:
    - master@nexendrie/nexendrie
  variables:
    DEPLOY_ENVIRONMENT: alpha

deploy:beta:
  <<: *deploy_job
  environment: beta
  only:
    - tags
  variables:
    DEPLOY_ENVIRONMENT: beta
