image: nexendrie/php:7.1

stages:
  - test
  - deploy

cache:
  paths:
  - vendor/

.job_template: &test_job
  stage: test

  services:
  - mysql

  variables:
    MYSQL_DATABASE: nexendrie
    MYSQL_ROOT_PASSWORD: root

  script:
  - phing test-ci

.job_template: &deploy_job
  stage: deploy

  script:
  - phing deploy

test:default:
  <<: *test_job
  retry: 2

test:php7.2:
  <<: *test_job
  image: nexendrie/php:7.2
  allow_failure: true

test:pgsql:
  <<: *test_job
  services:
  - postgres
  variables:
    POSTGRES_DB: nexendrie
    POSTGRES_USER: root
    POSTGRES_PASSWORD: root
  before_script:
  - cp tests/ci.neon tests/local.neon
  - php tools/pgsql_setup.php
  allow_failure: true

test:cc:
  <<: *test_job
  script:
  - phing test-ci-coverage
  coverage: '/(\d+\%) covered/'
  artifacts:
    name: "Code coverage"
    paths:
    - coverage.html
  retry: 2

deploy:alpha:
  <<: *deploy_job
  environment:
    name: alpha
    url: http://alpha.nexendrie.cz
  only:
    - master@nexendrie/nexendrie
  variables:
    DEPLOY_ENVIRONMENT: alpha

deploy:beta:
  <<: *deploy_job
  environment:
    name: beta
    url: https://beta.nexendrie.cz
  only:
    - tags@nexendrie/nexendrie
  variables:
    DEPLOY_ENVIRONMENT: beta
