image: php:7.0

.job_template: &test_job
  services:
  - mysql
  
  cache:
    paths:
    - vendor/
  
  variables:
    MYSQL_DATABASE: nexendrie
    MYSQL_ROOT_PASSWORD: root
  
  before_script:
  - mkdir app/temp
  - mkdir app/temp/cache
  - mkdir app/temp/sessions
  - mkdir app/log
  
  - apt-get update -yqq
  - apt-get install git -yqq
  - docker-php-ext-install mysqli
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar update --no-interaction --prefer-source -a

  - php setup_ci.php
  
  script:
  - ./vendor/bin/parallel-lint app -e php --exclude vendor --exclude app/temp
  - ./vendor/bin/phpcs --extensions=php . --standard=ruleset.xml --colors

test:php7:
  <<: *test_job

test:php71:
  image: php:7.1
  <<: *test_job
  allow_failure: true
