image: php:5.6

.job_template: &test_job
  services:
  - mysql
  
  cache:
    paths:
    - vendor/
  
  variables:
    MYSQL_DATABASE: nexendrie
    MYSQL_ROOT_PASSWORD: nexendrie
  
  before_script:
  - mkdir app/temp
  - mkdir app/temp/cache
  - mkdir app/temp/sessions
  - mkdir app/log
  
  - apt-get update -yqq
  - apt-get install git -yqq
  - docker-php-ext-install pdo_mysql
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar update --no-interaction --prefer-source -a
  
  script:
  - ./vendor/bin/parallel-lint app -e php --exclude vendor
  - ./vendor/bin/phpcs --extensions=php . --standard=ruleset.xml --colors

test:default:
  <<: *test_job

test:php7:
  image: php:7.0
  <<: *test_job
