include:
  - template: Dependency-Scanning.gitlab-ci.yml

image: nexendrie/php:7.3

stages:
  - install
  - test
  - deploy

.default_cache: &default_cache
  policy: pull
  paths:
    - vendor/

.test_job: &test_job
  stage: test
  services:
    - mariadb
  cache:
    <<: *default_cache
  variables:
    MYSQL_DATABASE: nexendrie
    MYSQL_ROOT_PASSWORD: root
  script:
    - phing test-ci
  retry: 2

.deploy_job: &deploy_job
  stage: deploy
  cache:
    <<: *default_cache
  dependencies: []
  script:
    - phing deploy

install:composer:
  stage: install
  script:
    - composer install --prefer-dist --no-progress --no-suggest --no-interaction
  cache:
    <<: *default_cache
    policy: pull-push

test:default:
  <<: *test_job

test:pgsql:
  <<: *test_job
  services:
    - postgres
  variables:
    POSTGRES_DB: nexendrie
    POSTGRES_USER: root
    POSTGRES_PASSWORD: root
  script:
    - phing test-ci-pgsql
  allow_failure: true
  retry: 0

test:cc:
  <<: *test_job
  script:
    - phing test-ci-coverage
  coverage: '/(\d+\%) covered/'
  artifacts:
    name: "Code coverage"
    paths:
      - coverage.html

test:css:
  stage: test
  image: node:lts-buster
  before_script:
    - npm install -g csslint
  script:
    - csslint styles

deploy:alpha:
  <<: *deploy_job
  environment:
    name: alpha
    url: https://alpha.nexendrie.cz
  only:
    - master@nexendrie/nexendrie
  variables:
    DEPLOY_ENVIRONMENT: alpha

deploy:beta:
  <<: *deploy_job
  environment:
    name: beta
    url: https://beta.nexendrie.cz
  only:
    - tags@nexendrie/nexendrie
  variables:
    DEPLOY_ENVIRONMENT: beta
