image: php:7.0

stages:
  - build
  - analyze
  - test

build:
  stage: build

  script:
  - mkdir app/temp
  - mkdir app/temp/cache
  - mkdir app/log

  - apt-get update -yqq
  - apt-get install git -yqq
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install --no-interaction --prefer-source -a

  cache:
    paths:
    - vendor

  artifacts:
    paths:
    - vendor
    - app/temp
    - app/log
    expire_in: 10 mins

analyze:lint:
  stage: analyze
  script:
  - ./vendor/bin/parallel-lint . -e php,phpt --exclude vendor --exclude app/temp --exclude tests/_temp

analyze:cs:
  stage: analyze
  script:
  - ./vendor/bin/phpcs --extensions=php,phpt . --standard=ruleset.xml --colors

.job_template: &test_job
  stage: test

  services:
  - mysql

  variables:
    MYSQL_DATABASE: nexendrie
    MYSQL_ROOT_PASSWORD: root
    APP_USER: admin
    APP_PASSWORD: qwerty

  before_script:
  - docker-php-ext-install mysqli
  - php ci/setup_db.php

  script:
  - ./vendor/bin/run-tests -p php tests

test:php7:
  <<: *test_job

test:php71:
  image: php:7.1
  <<: *test_job
  allow_failure: true
