image: nexendrie/php

stages:
  - test
  - deploy

cache:
  paths:
  - vendor/

.job_template: &test_job
  stage: test

  services:
  - mysql

  variables:
    MYSQL_DATABASE: nexendrie_test
    MYSQL_ROOT_PASSWORD: root
    APP_USER: admin
    APP_PASSWORD: qwerty

  script:
  - phing test-ci

.job_template: &deploy_job
  stage: deploy

  script:
  - phing deploy

test:default:
  <<: *test_job

test:cc:
  <<: *test_job
  script:
  - phing test-ci-coverage
  coverage: '/(\d+\%) covered/'
  artifacts:
    name: "Code coverage"
    paths:
    - coverage.html

deploy:alpha:
  <<: *deploy_job
  environment:
    name: alpha
    url: http://alpha.nexendrie.cz
  only:
    - master@nexendrie/nexendrie
  variables:
    DEPLOY_ENVIRONMENT: alpha

deploy:beta:
  <<: *deploy_job
  environment:
    name: beta
    url: https://beta.nexendrie.cz
  only:
    - tags
  variables:
    DEPLOY_ENVIRONMENT: beta
