build:
    environment:
        php:
            version: 8.1
            pecl_extensions:
                - pcov
        postgresql: false
        redis: false
        rabbitmq: false
        mysql: 5.5
    nodes:
        tests:
            cache:
                directories:
                    - vendor/
            dependencies:
                override:
                    - wget https://www.phing.info/get/phing-latest.phar && mv phing-latest.phar phing && chmod +x phing
            tests:
                override:
                    -
                        command: ./phing scrutinizer
                        analysis:
                            file: codesniffer.xml
                            format: 'general-checkstyle'
                        coverage:
                            file: coverage.xml
                            format: php-clover
                    -
                        command: ./vendor/bin/phpstan analyze --error-format=checkstyle --memory-limit 1G | tee phpstan.xml
                        analysis:
                            file: phpstan.xml
                            format: 'general-checkstyle'
                    - php-scrutinizer-run
