<?php
declare(strict_types=1);

use Phinx\Seed\AbstractSeed;

final class MountSeeder extends AbstractSeed {
  public function getDependencies(): array {
    return [UserSeeder::class];
  }

  public function run(): void {
    $this->table("mounts")
      ->insert([
        [
          'id' => 1,
          'name' => 'Mel',
          'gender' => 'male',
          'type' => 1,
          'owner' => 0,
          'price' => 50,
          'on_market' => true,
          'birth' => 1444838883,
          'hp' => 100,
          'damage' => 0,
          'armor' => 0,
          'auto_feed' => false,
        ],
        [
          'id' => 2,
          'name' => 'Erald',
          'gender' => 'male',
          'type' => 5,
          'owner' => 1,
          'price' => 5000,
          'on_market' => false,
          'birth' => 1444840086,
          'hp' => 100,
          'damage' => 6,
          'armor' => 4,
          'auto_feed' => false,
        ],
        [
          'id' => 3,
          'name' => 'Larna',
          'gender' => 'female',
          'type' => 1,
          'owner' => 0,
          'price' => 50,
          'on_market' => true,
          'birth' => 1444859395,
          'hp' => 100,
          'damage' => 0,
          'armor' => 0,
          'auto_feed' => false,
        ],
        [
          'id' => 4,
          'name' => 'Mil',
          'gender' => 'male',
          'type' => 1,
          'owner' => 0,
          'price' => 50,
          'on_market' => true,
          'birth' => 1444859656,
          'hp' => 100,
          'damage' => 0,
          'armor' => 0,
          'auto_feed' => false,
        ],
        [
          'id' => 5,
          'name' => 'Zimma',
          'gender' => 'female',
          'type' => 1,
          'owner' => 3,
          'price' => 50,
          'on_market' => true,
          'birth' => 1444859791,
          'hp' => 100,
          'damage' => 0,
          'armor' => 0,
          'auto_feed' => false,
        ],
        [
          'id' => 6,
          'name' => 'Ivlis',
          'gender' => 'male',
          'type' => 4,
          'owner' => 2,
          'price' => 1800,
          'on_market' => false,
          'birth' => 1446756290,
          'hp' => 100,
          'damage' => 3,
          'armor' => 5,
          'auto_feed' => false,
        ],
        [
          'id' => 7,
          'name' => 'Buris',
          'gender' => 'male',
          'type' => 2,
          'owner' => 0,
          'price' => 127,
          'on_market' => true,
          'birth' => 1447342669,
          'hp' => 100,
          'damage' => 0,
          'armor' => 1,
          'auto_feed' => false,
        ],
        [
          'id' => 8,
          'name' => 'Bila',
          'gender' => 'female',
          'type' => 2,
          'owner' => 3,
          'price' => 127,
          'on_market' => false,
          'birth' => 1447343032,
          'hp' => 100,
          'damage' => 1,
          'armor' => 3,
          'auto_feed' => false,
        ],
        [
          'id' => 9,
          'name' => 'Durhil',
          'gender' => 'young',
          'type' => 5,
          'owner' => 0,
          'price' => 5000,
          'on_market' => true,
          'birth' => 1447513936,
          'hp' => 100,
          'damage' => 3,
          'armor' => 2,
          'auto_feed' => false,
        ],
        [
          'id' => 10,
          'name' => 'Lana',
          'gender' => 'female',
          'type' => 4,
          'owner' => 4,
          'price' => 400,
          'on_market' => false,
          'birth' => 1455361161,
          'hp' => 100,
          'damage' => 3,
          'armor' => 5,
          'auto_feed' => false,
        ],
        [
          'id' => 11,
          'name' => 'Ihb An',
          'gender' => 'male',
          'type' => 3,
          'owner' => 0,
          'price' => 300,
          'on_market' => true,
          'birth' => 1465734704,
          'hp' => 100,
          'damage' => 1,
          'armor' => 0,
          'auto_feed' => false,
        ],
        [
          'id' => 12,
          'name' => 'Valdan',
          'gender' => 'male',
          'type' => 2,
          'owner' => 0,
          'price' => 100,
          'on_market' => true,
          'birth' => 1465735652,
          'hp' => 100,
          'damage' => 0,
          'armor' => 1,
          'auto_feed' => false,
        ],
      ])
      ->update();
  }
}
?>